#!/bin/bash

[ -n "$CIRCLECI_USER" ] || export CIRCLECI_USER=ubuntu
[ -n "$RUN_APT_UPDATE" ] || export RUN_APT_UPDATE=false

export CIRCLECI_HOME=/home/${CIRCLECI_USER}
export CIRCLECI_PKG_DIR=/opt/circleci

if ! [ -d $CIRCLECI_PKG_DIR ]; then
    mkdir -p $CIRCLECI_PKG_DIR
    chown -R $CIRCLECI_USER:$CIRCLECI_USER $CIRCLECI_PKG_DIR
fi

function as_user() {
    sudo -H -u ${CIRCLECI_USER} $@
}
export -f as_user

function maybe_run_apt_update() {
    if [ $RUN_APT_UPDATE = "true" ]; then
	apt-get update
    fi
}
export -f maybe_run_apt_update

[[ $SCRIPTS_PATH ]] || export SCRIPTS_PATH=/opt/circleci-provision-scripts

set -a
set -e

if [ "$VERBOSE" = "true" ]; then
  echo "enabling debug mode...."
  set -x
fi

export SHELLOPTS

for n in $SCRIPTS_PATH/*.sh
do
    source $n
done

install_$@
