#!/bin/bash

[ -n "$CIRCLECI_USER" ] || export CIRCLECI_USER=ubuntu
export CIRCLECI_HOME=/home/${CIRCLECI_USER}
export CIRCLECI_PKG_DIR=/opt/circleci

if ! [ -d $CIRCLECI_PKG_DIR ]; then
    mkdir -p $CIRCLECI_PKG_DIR
fi

chown -R $CIRCLECI_USER:$CIRCLECI_USER $CIRCLECI_PKG_DIR

function as_user() {
    sudo -H -u ${CIRCLECI_USER} $@
}
export -f as_user


[[ $SCRIPTS_PATH ]] || export SCRIPTS_PATH=/opt/circleci-provision-scripts

set -a
for n in $SCRIPTS_PATH/*.sh
do
    source $n
done

set -ex
install_$@
