#!/bin/bash

INSTALL=$1
INSTALL_VERSION=$2
INSTALL_IF_NEEDED=$3

[[ -n "${CIRCLECI_USER}" ]] || export CIRCLECI_USER=ubuntu
[[ -n "${RUN_APT_UPDATE}" ]] || export RUN_APT_UPDATE=false
[[ -n "${SCRIPTS_PATH}" ]] || export SCRIPTS_PATH=/opt/circleci-provision-scripts

export CIRCLECI_HOME=/home/${CIRCLECI_USER}
export CIRCLECI_PKG_DIR=/opt/circleci

[[ -d "${CIRCLECI_PKG_DIR}" ]] && CIRCLECI_PKG_DIR_EXISTS=true


function as_user() {
    sudo -H -u "${CIRCLECI_USER}" "$@"
}
export -f as_user

function maybe_run_apt_update() {
    if [ $RUN_APT_UPDATE = "true" ]; then
	apt-get update
    fi
}
export -f maybe_run_apt_update


if [[ -z "${CIRCLECI_PKG_DIR_EXISTS}" ]]; then
	mkdir -p "${CIRCLECI_PKG_DIR}"
elif [[ -n "${INSTALL_IF_NEEDED}" && -d "${CIRCLECI_PKG_DIR}/${INSTALL}/${INSTALL_VERSION}" ]]; then
	exit 0
fi

chown -R "${CIRCLECI_USER}:${CIRCLECI_USER}" "${CIRCLECI_PKG_DIR}"

set -a
set -e

if [ "$VERBOSE" = "true" ]; then
  echo "enabling debug mode...."
  set -x
fi

export SHELLOPTS

for n in $SCRIPTS_PATH/*.sh
do
    source $n
done

install_$@
