FROM circleci/build-image:scratch

RUN echo "this is enterprise image"
RUN echo "zzzzzzzzzzzzzz"

# Undivert upstart
# You shouldn't change the line unless you understad the consequence
RUN rm /usr/sbin/policy-rc.d && rm /sbin/initctl && dpkg-divert --rename --remove /sbin/initctl

LABEL circleci.user="ubuntu"
