#!/bin/bash


set -e

echoerr() { echo "$@" 1>&2; }

function usage() {
    echoerr "Utility for exporting Docker container filesystems"
    echoerr "Usage: $0 <image-id> > tarball.tar.gz"
    echoerr "   e.g. $0 test-container:0.0.1 > test-container_0.0.1.tar.gz"
    exit 1
}

if [  $# -ne 1 ]
then
	echoerr 'Missing docker image name'
        usage
fi

[ ! -t 1 ] || {
	echoerr 'missing file redirection.  Refusing to pipe to terminal'
	usage
}

IMAGE_ID=$1

(
    docker run --rm=true "${IMAGE_ID}" \
        tar --create --gzip --one-file-system \
	    --exclude='/tmp/*' --exclude='.dockerinit' --exclude='.dockerenv' \
            --transform 's|^|rootfs/|S' \
            -f - / /dev
)
echoerr "Image exported: ${IMAGE_ID}"
exit 0
